### ISSUE TITLE
Is it possible to add user name and computer name also?

### ISSUE THREAD

**Issue by baur** [doxakis/Generic-SQL-Audit-Trail#2]
Is it possible to add user name and computer name also?

**Comment by doxakis** [comment]
Hi,

yes, you will have to modify the script and add new columns.

To get the user name:
SELECT SYSTEM_USER

Machine name and sql instance name
SELECT CAST(SERVERPROPERTY('ServerName') AS VARCHAR(255))

I based the script on the following example :
https://www.simple-talk.com/sql/database-administration/pop-rivetts-sql-server-faq-no.5-pop-on-the-audit-trail/

For my use cases, it was not really useful the user name. So I removed the column.
It was always the same. (the application sql login)

Thanks!
