### ISSUE TITLE
Set audit 'Insert or Update or Delete' only

### ISSUE THREAD

**Issue by baur** [doxakis/Generic-SQL-Audit-Trail#4]
Set audit 'Insert or Update or Delete' only

Maybe create some table as **AuditTable** with fields
TableName: owner.TableName
Columns: if empty then all if list col1, col2 then audit only by list
Action: if empty then audit all actions if listed then only this actions

**Comment by doxakis** [comment]
Hi,

sure you can add another table. But if you want more flexibility, you can edit the generated triggers at the table level or database level.

At the database level, you can modify how trigger work on new tables.

At the table level, you will find something similar to :

IF (SUBSTRING(COLUMNS_UPDATED(), @char, 1) & @mask) > 0
										   OR @Type IN ('I','D')
		   BEGIN
			   SELECT @sql = '
					INSERT Audit ( Type, 
…

All you have to do is to edit the condition (which determine if it has to add an entry in the Audit table).

So, if you want insert only :
IF @Type IN ('I')
…

If you want update only :
IF (SUBSTRING(COLUMNS_UPDATED(), @char, 1) & @mask) > 0
…

If you want delete only :
IF @Type IN (‘D’)
…

Or, any combination.

To filter columns, you can use @fieldname in the condition.

Please note, if you use different schema, it will not work out of the box.
Some work has to be done to support it.

I hope you find it useful ! :)

**Comment by baur** [comment]
Maybe filter by Audit table trigger? All triggers will works usually but not all will be writes to Audit table ...

**Comment by doxakis** [comment]
Hi,

Right now, there is no trigger on the Audit table.

Maybe it could be the solution to filter the inserted rows (on Audit table) and exclude some rows.

If you want to, you can submit a pull request.

Please note, I want to keep it backward compatible.
If you have to introduce some breaking changes, it would be great to create another script. (ex: version 2)

So I can keep the old version for applications which used it.

To support user name and computer name, there could be some options at the beginning of the script to specify which one are desired.

Thanks.
