### ISSUE TITLE
Trigger cannot handled XML field

### ISSUE THREAD

**Issue by berndesj** [doxakis/Generic-SQL-Audit-Trail#6]
hello

nice trigger works for  me at 95%.

i receive an error when trigger is assign to a Table containing a XML field.

Any suggestion how to be able to handle XML field old and new value.

Thank's

**Comment by doxakis** [comment]
Hi,
I didn't had to handle xml field when I were using it.
I will check it in the next few days for a solution.
Maybe I can add a check if it's a xml field and handle it differently.
Thanks.

**Comment by doxakis** [comment]
Hi,

I think the issue should be fixed now.

Here is my test case:

Test table:
```
DROP TABLE IF EXISTS dbo.Products
GO
CREATE TABLE dbo.Products (
	IDPerson int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Title varchar(20) NOT NULL,
	Price DECIMAL NOT NULL,
	Qte INT NOT NULL,
	Items XML)
GO
```

I run the script: "Install audit trail script for SQL Server Database.sql"

Performing some operations:
```
DELETE FROM dbo.Products

INSERT INTO dbo.Products (Title, Price, Qte, Items)
VALUES ('Aaaa', 10.99, 1, '<items><item>11</item><item>22</item></items>')

INSERT INTO dbo.Products (Title, Price, Qte, Items)
VALUES ('Bbbb', 4.99, 8, NULL)

UPDATE p
SET Price = Price + 10
	, Items = '<items><item>11</item><item>55</item></items>'
	, Title = 'Cccc'
FROM dbo.Products p
WHERE Title = 'Aaaa'

DELETE FROM dbo.Products
WHERE Title = 'Bbbb'
```

I got the error:
The XML data type cannot be compared or sorted, except when using the IS NULL operator.

The issue look like the comparison of xml fields.

ex:

```
DECLARE @xml1 XML = '<a></a>'
DECLARE @xml2 XML = '<b></b>'
SELECT 1 WHERE @xml1 <> @xml2
```

The fix were to convert it to varchar(max) before comparison.

```
DECLARE @xml1 XML = '<a></a>'
DECLARE @xml2 XML = '<b></b>'
SELECT 1 WHERE convert(varchar(max), @xml1) <> convert(varchar(max), @xml2)
```
